name: Check for console.log

on:
  pull_request:
    types: [opened, reopened, synchronize]

runs:
  using: "bash"

jobs:
  check_console_log:
    name: Check for console.log statements
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for console.log
        run: |
          #!/bin/bash
          set -e

          # Search for console.log statements in changed files
          if git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF | xargs grep -En '\bconsole\.log\b'; then
            echo "ERROR: Console.log statements found. Please remove them before merging the pull request."
            exit 1
          else
            echo "No console.log statements found. Proceeding with the pull request."
          fi
