name: "Check Logs"
description: "An action to check console statements in code"
inputs: {} # No inputs defined for this action
outputs: {} # No outputs defined for this action
runs:
  using: "node12" # or specify any supported environment
  main: "check_logs.sh"
